version: '3.8'

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: always
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - ticketz_network

  frontend:
    environment:
      - REACT_APP_BACKEND_URL=https://${BACKEND_HOST}
      - REACT_APP_FRONTEND_URL=https://${FRONTEND_HOST}
    depends_on:
      - cloudflared

  backend:
    environment:
      - BACKEND_URL=https://${BACKEND_HOST}
      - FRONTEND_URL=https://${FRONTEND_HOST}
    depends_on:
      - cloudflared

networks:
  ticketz_network:
    driver: bridge 